### PR TITLE
Remove console.log('fit')

### PR DESCRIPTION
**Pull request by mbardelmeijer**
Removed unnecessarily console.log for production usage.

### CODE REVIEW

**Comment by artpolikarpov** [comment]
No need. When you `grunt` all of `console.*` gone away.

**Comment by mbardelmeijer** [comment]
Ok, but the .min,js version still contains it. (search for console.log in https://cdnjs.cloudflare.com/ajax/libs/fotorama/4.6.3/fotorama.min.js)

**Comment by kevin1024** [comment]
I'm seeing this as well.

**Comment by Rikk** [comment]
Could it be that the minified file (*fotorama.min.js*) hosted by cloudflare was manually minified based on the official release¹, which is not minified (https://github.com/artpolikarpov/fotorama/issues/361) and has this *console.log* not commented?
¹ https://github.com/artpolikarpov/fotorama/releases/download/4.6.3/fotorama-4.6.3.zip

**Comment by TiGR** [comment]
It is [still present](https://github.com/artpolikarpov/fotorama-bower/blob/master/fotorama.js#L1296) in fotorama-bower.

**Comment by marcvangend** [comment]
Thank you. When can we expect a new release?

**Pull request closed without merging**
